-- MySQL Script generated by MySQL Workbench
-- Thu Sep 10 14:36:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veterinários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veterinários` (
  `CRMv` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_Admissão` DATE NOT NULL,
  `Salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`CRMv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animais` (
  `Nome` VARCHAR(45) NOT NULL,
  `Ano de nascimento` YEAR NOT NULL,
  `Raça` VARCHAR(45) NOT NULL,
  `Codigo` INT NOT NULL,
  `Clientes_CPF` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Animais_Clientes1_idx` (`Clientes_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Animais_Clientes1`
    FOREIGN KEY (`Clientes_CPF`)
    REFERENCES `mydb`.`Clientes` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consultas` (
  `idConsultas` INT NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `data e hora` DATETIME NOT NULL,
  `Animais_Codigo` INT NOT NULL,
  `Veterinários_CRMv` INT NOT NULL,
  PRIMARY KEY (`idConsultas`),
  INDEX `fk_Consultas_Animais1_idx` (`Animais_Codigo` ASC) VISIBLE,
  INDEX `fk_Consultas_Veterinários1_idx` (`Veterinários_CRMv` ASC) VISIBLE,
  CONSTRAINT `fk_Consultas_Animais1`
    FOREIGN KEY (`Animais_Codigo`)
    REFERENCES `mydb`.`Animais` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Veterinários1`
    FOREIGN KEY (`Veterinários_CRMv`)
    REFERENCES `mydb`.`Veterinários` (`CRMv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
